SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS as I
JOIN ANIMAL_OUTS as O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE "%Intact%" and (SEX_UPON_OUTCOME LIKE "%Neutered%" OR SEX_UPON_OUTCOME LIKE "%Spayed%")
ORDER BY I.ANIMAL_ID