SELECT FH.FLAVOR
FROM FIRST_HALF as FH
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) as J
ON FH.FLAVOR = J.FLAVOR
GROUP BY FH.FLAVOR
ORDER BY SUM(FH.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
LIMIT 3