SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE NOT TLNO = 'NULL' AND MONTH(DATE(DATE_OF_BIRTH)) = '03' AND GENDER = 'w'
ORDER BY MEMBER_ID ASC;
