SELECT USER_ID, NICKNAME, SUM(PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD as ugb
JOIN USED_GOODS_USER as ugu
ON ugb.WRITER_ID = ugu.USER_ID
WHERE STATUS = 'DONE'
GROUP BY ugb.WRITER_ID # ???
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES