SELECT CCC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR as CCC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as CCCH
ON CCC.CAR_ID = CCCH.CAR_ID
WHERE CAR_TYPE = '세단' and MONTH(START_DATE) = 10
GROUP BY CCC.CAR_ID
ORDER BY CCC.CAR_ID DESC