SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO as FI1
JOIN FISH_NAME_INFO as FNI
ON FI1.FISH_TYPE = FNI.FISH_TYPE
WHERE LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO as FI2
    WHERE FI1.FISH_TYPE = FI2.FISH_TYPE
    GROUP BY FISH_TYPE
)
ORDER BY ID