SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK as b
JOIN BOOK_SALES as bs
ON b.BOOK_ID = bs.BOOK_ID
WHERE bs.SALES_DATE >= '2022-01-01' and bs.SALES_DATE < '2022-02-01'
GROUP BY CATEGORY
ORDER BY CATEGORY